/**
 * Curated vocabulary used by the deterministic pattern generator. Each list
 * feeds one or more templates; the cross product yields ~5,000 distinct,
 * natural-sounding prompt-improvement patterns for Vectorize.
 */
export const ROLES = [
  "a B2B marketing strategist",
  "a content marketer",
  "a senior copy editor",
  "an SEO specialist",
  "a sales coach",
  "a cold email copywriter",
  "a product manager",
  "a data analyst",
  "a financial analyst",
  "a UX designer",
  "a UX researcher",
  "a brand strategist",
  "a social media manager",
  "a LinkedIn ghostwriter",
  "a blog writer",
  "a technical writer",
  "a proofreader",
  "a public speaking coach",
  "a recruiter",
  "an HR specialist",
  "a customer support lead",
  "an account executive",
  "a demand generation manager",
  "a growth marketer",
  "an email marketer",
  "a landing page copywriter",
  "a video scriptwriter",
  "a podcast host",
  "a journalist",
  "a grant writer",
  "a proposal writer",
  "a pitch deck writer",
  "a business plan consultant",
  "a startup advisor",
  "a project manager",
  "an operations manager",
  "an executive assistant",
  "a personal finance coach",
  "a nutrition coach",
  "a fitness trainer",
  "a career coach",
  "a resume writer",
  "an interview coach",
  "a negotiation coach",
  "a pricing strategist",
  "a market researcher",
  "a competitive analyst",
  "an SQL analyst",
  "a spreadsheet expert",
  "a chatbot designer",
  "an API documentation writer",
  "a developer advocate",
  "a junior developer mentor",
  "a code reviewer",
  "a QA specialist",
  "an accessibility specialist",
  "a legal analyst",
  "a compliance officer",
  "a crisis communications advisor",
] as const;

export const FORMATS = [
  "a bulleted list",
  "a numbered list",
  "a markdown table",
  "valid JSON",
  "a CSV",
  "an outline with headings",
  "a short email",
  "a LinkedIn post",
  "a Twitter/X thread",
  "a blog outline",
  "a summary with three sections",
  "a checklist",
  "an FAQ",
  "a pros and cons table",
  "a two-column comparison table",
  "a one-page memo",
  "a slide deck outline",
  "an abstract",
  "a press release draft",
  "a subject line plus body",
  "five bullet points",
  "a paragraph of up to 100 words",
  "a step-by-step guide",
  "an executive summary",
  "a script",
  "a proposal",
  "a landing page hero and subhead",
  "a questionnaire",
  "a SWOT analysis",
  "a mind-map outline",
] as const;

export const CONTEXTS = [
  "we are a 12-person SaaS startup",
  "we sell analytics for support teams",
  "our audience is non-technical small business owners",
  "we have 400 customers",
  "we just launched a new feature",
  "our brand tone is friendly and concise",
  "we operate in B2B in Europe",
  "our readers are CTOs",
  "we are preparing for a product launch",
  "our deadline is next Friday",
  "we already have a draft in Google Docs",
  "this is for our weekly newsletter",
  "our competitors are large and slow",
  "we have a limited budget",
  "our team is fully remote",
  "we serve marketing leaders",
  "we are rebranding next quarter",
  "our customers complained about onboarding",
  "we are A/B testing a new pricing page",
  "this is for an internal training session",
  "our support volume doubled last month",
  "we are hiring a new team",
  "our CEO wants a one-pager",
  "we target mid-market companies",
  "we speak to founders daily",
  "our product integrates with Slack",
  "we are a non-profit",
  "we serve healthcare clinics",
  "our trial conversion is low",
  "we see strong churn in month three",
] as const;

export const TOPICS = [
  "onboarding flows",
  "pricing strategy",
  "feature adoption",
  "customer churn",
  "sales outreach",
  "email deliverability",
  "SEO keywords",
  "product roadmap",
  "market positioning",
  "competitive differentiation",
  "user interviews",
  "retention metrics",
  "activation rate",
  "trial-to-paid conversion",
  "support ticket deflection",
  "community engagement",
  "newsletter growth",
  "content pillars",
  "brand voice",
  "landing page conversion",
  "referral programs",
  "customer testimonials",
  "integration partners",
  "API design",
  "error messages",
  "accessibility",
  "localization",
  "data privacy",
  "security compliance",
  "billing and invoicing",
  "onboarding emails",
  "lifecycle emails",
  "webinars",
  "thought leadership",
  "case studies",
  "product demos",
  "feedback loops",
  "experimentation",
  "our north star metric",
  "cohort analysis",
] as const;

export const EXAMPLES = [
  "a recent piece of writing you like",
  "a tweet that performed well",
  "our previous newsletter issue",
  "a competitor's landing page",
  "an internal doc on our wiki",
  "a real customer email",
  "the tone of our help center",
  "a blog post we published last month",
  "the script of our launch video",
  "an old pitch deck",
  "a screenshot of our dashboard",
  "a note from our CEO",
  "a template from our sales playbook",
  "our onboarding email sequence",
  "a chapter from our whitepaper",
  "an excerpt from our user manual",
  "a review a customer wrote",
  "our tagline and logo",
  "a past campaign we loved",
  "a sample from our style guide",
] as const;
